Pandas is a powerful data analyst library, and pandas data structures include: **series, data frames**, and panels (3D)

Series is a one dimensional labelled homogeneous array.

Dataframe is a two dimensional hetergenous tabular data structure - (Series + Series).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.__version__

'1.5.3'

In [ ]:
a = [True, "Name", 6, 7.8, (5, 8)]
s1 = pd.Series(a)

s1

0      True
1      Name
2         6
3       7.8
4    (5, 8)
dtype: object

In [ ]:
s2 = pd.Series([54, 78, 21, 342, 654, 93], index = ["a", "b", "c", "d", "e", "f"], dtype = float)
s2

a     54.0
b     78.0
c     21.0
d    342.0
e    654.0
f     93.0
dtype: float64

In [ ]:
a1 = pd.Series(0.5, index = [1, 2, 3])
a1

1    0.5
2    0.5
3    0.5
dtype: float64

In [ ]:
a2 = pd.Series({"a": 1, "b": 2, "c": 3})
a2

a    1
b    2
c    3
dtype: int64

In [ ]:
a2["b"]

2

In [ ]:
a3 = pd.Series([1, 2, 3, 4])
a4 = pd.Series([1, 2, 3])

a3 + a4

0    2.0
1    4.0
2    6.0
3    NaN
dtype: float64

In [ ]:
a5 = [[1, "Madhava", 2],
      [2, "Sahil", 3],
      [3, "Tavin", 4]]

df = pd.DataFrame(a5)

df

   0        1  2
0  1  Madhava  2
1  2    Sahil  3
2  3    Tavin  4

In [ ]:
a6 = {"id": [1, 2, 3], "name": ["Madhava", "Sahil", "Tavin"], "age": [2, 3, 4]}
df1 = pd.DataFrame(a6)
df1

   id     name  age
0   1  Madhava    2
1   2    Sahil    3
2   3    Tavin    4

In [ ]:
ids = pd.Series([1, 2, 3])
names = pd.Series(["Madhava", "Sahil", "Tavin"])
ages = pd.Series([2, 3, 4])

a7 = {"id": ids, "name": names, "age": ages}
a7

{'id': 0    1
 1    2
 2    3
 dtype: int64,
 'name': 0    Madhava
 1      Sahil
 2      Tavin
 dtype: object,
 'age': 0    2
 1    3
 2    4
 dtype: int64}

In [ ]:
df3 = pd.read_csv("/content/tips1.csv")
df3

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df3.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [ ]:
df3.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
df3.head(210)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
205,16.47,3.23,Female,Yes,Thur,Lunch,3,5.49,Carly Reyes,4787787236486,Thur8084
206,26.59,3.41,Male,Yes,Sat,Dinner,3,8.86,Daniel Owens,38971087967574,Sat1
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505
208,24.27,2.03,Male,Yes,Sat,Dinner,2,12.14,Jason Carter,4268942915626180,Sat6048
209,12.76,2.23,Female,Yes,Sat,Dinner,2,6.38,Sarah Cunningham,341876516331163,Sat1274

In [ ]:
df3.tail(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df4 = pd.read_csv("/content/tips1.csv", nrows = 10)
df4

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775

In [ ]:
df5 = pd.read_csv("/content/tips1.csv", nrows = 10, usecols = [2, 5])
df5

      sex    time
0  Female  Dinner
1    Male  Dinner
2    Male  Dinner
3    Male  Dinner
4  Female  Dinner
5    Male  Dinner
6    Male  Dinner
7    Male  Dinner
8    Male  Dinner
9    Male  Dinner

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sex     10 non-null     object
 1   time    10 non-null     object
dtypes: object(2)
memory usage: 288.0+ bytes

In [ ]:
df6 = pd.read_csv("/content/tips1.csv", skiprows = [0])
df6

,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
0,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
1,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
2,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
3,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
4,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
...,...,...,...,...,...,...,...,...,...,...,...
238,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
239,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
240,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
241,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
242,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df7 = pd.read_csv("/content/tips1.csv")
df7

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df8 = pd.read_csv("/content/tips1.csv", index_col = "Payer Name")
df8

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672

In [ ]:
df9 = pd.read_csv("/content/tips1.csv", index_col = 8)
df9

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672

In [ ]:
#Grabbing Columns
df3[['total_bill', 'Payment ID']]

     total_bill Payment ID
0         16.99    Sun2959
1         10.34    Sun4608
2         21.01    Sun4458
3         23.68    Sun5260
4         24.59    Sun2251
..          ...        ...
239       29.03    Sat2657
240       27.18    Sat1766
241       22.67    Sat3880
242       17.82      Sat17
243       18.78    Thur672

[244 rows x 2 columns]

In [ ]:
df3["tip_percentage"] = (df3["tip"] / df3["total_bill"]) * 100
df3

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.974441

In [ ]:
df3['tip_percentage'] = np.round(df3['tip_percentage'], 2)
df3

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97

In [ ]:
df3.set_index("Payer Name")

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID,tip_percentage
Payer Name,,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959,5.94
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608,16.05
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458,16.66
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260,13.98
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657,20.39
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766,7.36
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880,8.82
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17,9.82
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672,15.97

In [ ]:
df3 = df3.reset_index()

In [ ]:
df3

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82
243,243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97

In [ ]:
df10 = pd.read_csv("/content/tips1.csv", dtype = {"size": float})
df10

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2.0,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3.0,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3.0,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2.0,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4.0,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3.0,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2.0,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2.0,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2.0,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2.0,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df11 = pd.read_csv("/content/tips1.csv", dtype = {"CC Number": float})
df11

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560325e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478071e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011812e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676138e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832733e+15,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.296069e+15,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.506806e+15,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011892e+15,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375221e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511452e+15,Thur672

In [ ]:
#Ascessing Dataframes

#pandas loc : ascess groups of rows and columns by labels

df12 = pd.read_csv("/content/tips1.csv")
df12

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df3.loc[0]

index                                0
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Payment ID                     Sun2959
tip_percentage                    5.94
Name: 0, dtype: object

In [ ]:
df3.loc[0, "total_bill"]

16.99

In [ ]:
df3.loc[0:5, "total_bill"]

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
5    25.29
Name: total_bill, dtype: float64

In [ ]:
df3[df3["size"] == 3]
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             244 non-null    int64
 1   total_bill        244 non-null    float64
 2   tip               244 non-null    float64
 3   sex               244 non-null    object
 4   smoker            244 non-null    object
 5   day               244 non-null    object
 6   time              244 non-null    object
 7   size              244 non-null    int64
 8   price_per_person  244 non-null    float64
 9   Payer Name        244 non-null    object
 10  CC Number         244 non-null    int64
 11  Payment ID        244 non-null    object
 12  tip_percentage    244 non-null    float64
dtypes: float64(4), int64(3), object(6)
memory usage: 24.9+ KB

In [ ]:
df3[(df3["total_bill"] < 30) & ~(df3["sex"] == "Male")]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68
14,14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,30016702287574,Sun3848,20.36
16,16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4240025044626033,Sun9715,16.17
18,18,16.97,3.50,Female,No,Sun,Dinner,3,5.66,Laura Martinez,30422275171379,Sun2789,20.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,225,16.27,2.50,Female,Yes,Fri,Lunch,2,8.14,Whitney Arnold,3579111947217428,Fri6665,15.37
226,226,10.09,2.00,Female,Yes,Fri,Lunch,2,5.04,Ruth Weiss,5268689490381635,Fri6359,19.82
229,229,22.12,2.88,Female,Yes,Sat,Dinner,2,11.06,Jennifer Russell,4793003293608,Sat3943,13.02
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36
243,243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97

In [ ]:
df3[(df3["day"] == "Sun") | (df3["day"] == "Sat")]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777,13.03
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82

In [ ]:
df3[df3["day"].isin(["Sat", "Sun"])]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777,13.03
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82

In [ ]:
def CCNum(num):
  return str(num)[-4:]

In [ ]:
df3["New CC Number"] = df3["CC Number"].apply(CCNum)
df3

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94,3410
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,9230
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66,1322
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98,5994
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68,7221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39,2842
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36,5404
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82,7196
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82,0950
243,243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97,8139

In [ ]:
def status(num):
  if num < 10:
    return "Cheap"
  elif num < 30 and num > 10:
    return "Affordable"
  elif num > 30:
    return "Expensive"

In [ ]:
df3["Status"] = df3["total_bill"].apply(status)
df3

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94,3410,Affordable
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,9230,Affordable
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66,1322,Affordable
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98,5994,Affordable
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68,7221,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39,2842,Affordable
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36,5404,Affordable
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82,7196,Affordable
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82,0950,Affordable
243,243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97,8139,Affordable

In [ ]:
df3.sort_values(["total_bill"])

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
67,67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,32.57,5267,Cheap
92,92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,17.39,6392,Cheap
111,111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,13.79,6887,Cheap
172,172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,30432617123103,Sun9209,71.03,3103,Cheap
149,149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,4823139288341889,Thur6321,26.63,1889,Cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,7.72,9910,Expensive
156,156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,10.38,3321,Expensive
59,59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,13.94,0595,Expensive
212,212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,18.62,5212,Expensive
170,170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,19.68,8236,Expensive

In [ ]:
df3["total_bill"].max()

50.81

In [ ]:
df3["total_bill"].idxmax()

170

In [ ]:
df3["total_bill"].min()

3.07

In [ ]:
df3["total_bill"].idxmin()

67

In [ ]:
df3.iloc[170]

index                            170
total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Payment ID                   Sat1954
tip_percentage                 19.68
New CC Number                   8236
Status                     Expensive
Name: 170, dtype: object

In [ ]:
df3.iloc[67]

index                             67
total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
tip_percentage                 32.57
New CC Number                   5267
Status                         Cheap
Name: 67, dtype: object

In [ ]:
df3.iloc[68:90, 1]

68    20.23
69    15.01
70    12.02
71    17.07
72    26.86
73    25.28
74    14.73
75    10.51
76    17.92
77    27.20
78    22.76
79    17.29
80    19.44
81    16.66
82    10.07
83    32.68
84    15.98
85    34.83
86    13.03
87    18.28
88    24.71
89    21.16
Name: total_bill, dtype: float64

In [ ]:
df3.iloc[[1, 2, 3]]

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,9230,Affordable
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66,1322,Affordable
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98,5994,Affordable

In [ ]:
df3

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94,3410,Affordable
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,9230,Affordable
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66,1322,Affordable
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98,5994,Affordable
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68,7221,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39,2842,Affordable
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36,5404,Affordable
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82,7196,Affordable
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82,0950,Affordable
243,243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97,8139,Affordable

In [ ]:
df3.drop(243)

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94,3410,Affordable
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,9230,Affordable
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66,1322,Affordable
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98,5994,Affordable
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68,7221,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777,13.03,3727,Expensive
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39,2842,Affordable
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36,5404,Affordable
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82,7196,Affordable
242,242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82,0950,Affordable

In [ ]:
df3.drop([240, 241, 242, 243])

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94,3410,Affordable
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,9230,Affordable
2,2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66,1322,Affordable
3,3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98,5994,Affordable
4,4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68,7221,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615,12.41,7605,Affordable
236,236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,7.94,3965,Affordable
237,237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929,3.56,5508,Expensive
238,238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777,13.03,3727,Expensive
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39,2842,Affordable

In [ ]:
df3.drop(["smoker", "Payment ID"], axis = 1)

,index,total_bill,tip,sex,day,time,size,price_per_person,Payer Name,CC Number,tip_percentage,New CC Number,Status
0,0,16.99,1.01,Female,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,5.94,3410,Affordable
1,1,10.34,1.66,Male,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,16.05,9230,Affordable
2,2,21.01,3.50,Male,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,16.66,1322,Affordable
3,3,23.68,3.31,Male,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,13.98,5994,Affordable
4,4,24.59,3.61,Female,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,14.68,7221,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,20.39,2842,Affordable
240,240,27.18,2.00,Female,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,7.36,5404,Affordable
241,241,22.67,2.00,Male,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,8.82,7196,Affordable
242,242,17.82,1.75,Male,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,9.82,0950,Affordable
243,243,18.78,3.00,Female,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,15.97,8139,Affordable

In [ ]:
df3["size"].unique()

array([2, 3, 4, 1, 6, 5])

In [ ]:
df3["size"].nunique()

6

In [ ]:
time_map = {"Dinner": "D", "Lunch": "L"}

df3["time"].map(time_map)

0      D
1      D
2      D
3      D
4      D
      ..
239    D
240    D
241    D
242    D
243    D
Name: time, Length: 244, dtype: object

In [ ]:
#Returns True for first instance of duplicated value

df3.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [ ]:
DataF = pd.Series([1, 2, 2], index = ["a", "b", "c"], dtype = float)

DataF.duplicated()

a    False
b    False
c     True
dtype: bool

In [ ]:
DataF.drop_duplicates()

a    1.0
b    2.0
dtype: float64

In [ ]:
DataF.sample(2)

a    1.0
c    2.0
dtype: float64

In [ ]:
df3.sample(frac = 0.1)

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
203,203,16.40,2.50,Female,Yes,Thur,Lunch,2,8.20,Toni Brooks,3582289985920239,Thur7770,15.24,0239,Affordable
38,38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4427601595688633,Sat4056,12.36,8633,Affordable
33,33,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,377742985258914,Sat6649,11.84,8914,Affordable
56,56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903,7.89,3226,Expensive
36,36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3527691170179398,Sat9139,12.26,9398,Affordable
11,11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686,14.18,0969,Expensive
171,171,15.81,3.16,Male,Yes,Sat,Dinner,2,7.90,David Hall,502004138207,Sat6750,19.99,8207,Affordable
86,86,13.03,2.00,Male,No,Thur,Lunch,2,6.52,Derek Thomas,213161022097557,Thur6793,15.35,7557,Affordable
119,119,24.08,2.92,Female,No,Thur,Lunch,4,6.02,Melanie Jordan,676212062720,Thur8063,12.13,2720,Affordable
42,42,13.94,3.06,Male,No,Sun,Dinner,2,6.97,Bryan Brown,36231182760859,Sun1699,21.95,0859,Affordable
196,196,10.34,2.00,Male,Yes,Thur,Lunch,2,5.17,Eric Martin,30442491190342,Thur9862,19.34,0342,Affordable
219,219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,Sat8863,10.25,3252,Expensive
200,200,18.71,4.00,Male,Yes,Thur,Lunch,3,6.24,Jason Conrad,4581233003487,Thur6048,21.38,3487,Affordable
26,26,13.37,2.00,Male,No,Sat,Dinner,2,6.68,Kyle Avery,6531339539615499,Sat6651,14.96,5499,Affordable
47,47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677,18.52,4186,Expensive
1,1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,9230,Affordable
194,194,16.58,4.00,Male,Yes,Thur,Lunch,2,8.29,Benjamin Weber,676210011505,Thur9318,24.13,1505,Affordable
231,231,15.69,3.00,Male,Yes,Sat,Dinner,3,5.23,Jason Parks,4812333796161,Sat6334,19.12,6161,Affordable
20,20,17.92,4.08,Male,No,Sat,Dinner,2,8.96,Thomas Rice,4403296224639756,Sat1709,22.77,9756,Affordable
173,173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3577115550328507,Sun9335,9.98,8507,Expensive
14,14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,30016702287574,Sun3848,20.36,7574,Affordable
214,214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374,23.07,1962,Affordable
65,65,20.08,3.15,Male,No,Sat,Dinner,3,6.69,Justin Dixon,180021262464926,Sat6840,15.69,4926,Affordable
29,29,19.65,3.00,Female,No,Sat,Dinner,2,9.82,Melinda Murphy,5489272944576051,Sat2467,15.27,6051,Affordable

In [ ]:
df3.nlargest(10, "tip")

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
170,170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,19.68,8236,Expensive
212,212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,18.62,5212,Expensive
23,23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,19.23,9808,Expensive
59,59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,13.94,0595,Expensive
141,141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,19.53,8508,Expensive
183,183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059,28.05,9162,Affordable
214,214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374,23.07,1962,Affordable
47,47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677,18.52,4186,Expensive
239,239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39,2842,Affordable
88,88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003,23.67,9955,Affordable

In [ ]:
df3.nsmallest(10, "tip")

,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage,New CC Number,Status
67,67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,32.57,5267,Cheap
92,92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,17.39,6392,Cheap
111,111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,13.79,6887,Cheap
236,236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,7.94,3965,Affordable
0,0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94,3410,Affordable
215,215,12.90,1.10,Female,Yes,Sat,Dinner,2,6.45,Jessica Owen,4726904879471,Sat6983,8.53,9471,Affordable
237,237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929,3.56,5508,Expensive
75,75,10.51,1.25,Male,No,Sat,Dinner,2,5.26,Kenneth Hayes,213142079731108,Sat5056,11.89,1108,Affordable
135,135,8.51,1.25,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,4320272020376174,Thur6600,14.69,6174,Cheap
235,235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615,12.41,7605,Affordable

***Handling The Missing Values.***

In [ ]:
ms = pd.read_csv("/content/movie_scores.csv")

In [ ]:
ms

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [ ]:
ms.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [ ]:
ms[ms["first_name"].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.isnull().sum()

first_name          1
last_name           1
age                 1
sex                 1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [ ]:
(ms.isnull().sum()).sum()

8

In [ ]:
ms[ms["pre_movie_score"].isnull() & ms["sex"].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [ ]:
ms.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
#Specifies to remove a row/coloumn when any of the values is Null
ms.dropna(how = "any")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#Specifies to remove a row/coloumn when all of the values are Null
ms.dropna(how = "all")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#Specifies to remove a row/coloumn when all of the values are Null
ms.dropna(how = "any", axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
#Specifies to remove a row/coloumn when all of the values are Null
ms.dropna(how = "all", axis = 1)

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
#look for at least not null values, if thresh value = 1 then there should be at least 1 not null or else it drops.
ms.dropna(thresh = 1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#look for at least not null values, if thresh value = 1 then there should be at least 1 not null or else it drops.
ms.dropna(thresh = 2)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#look for at least not null values, if thresh value = 1 then there should be at least 1 not null or else it drops.
ms.dropna(thresh = 3)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#look for at least not null values, if thresh value = 1 then there should be at least 1 not null or else it drops.
ms.dropna(thresh = 4)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#look for at least not null values, if thresh value = 1 then there should be at least 1 not null or else it drops.
ms.dropna(thresh = 5)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.dropna(subset = ["sex"], inplace = True)

In [ ]:
ms

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms = pd.read_csv("/content/movie_scores.csv")

In [ ]:
ms

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.fillna(1, inplace = True)

In [ ]:
ms

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1          1         1   1.0   1              1.0               1.0
2       Hugh   Jackman  51.0   m              1.0               1.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna(0)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1          1         1   1.0   1              1.0               1.0
2       Hugh   Jackman  51.0   m              1.0               1.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms = pd.read_csv("/content/movie_scores.csv")

In [ ]:
ms

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.fillna(method = "ffill")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna(method = "pad")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna(method = "bfill")

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1       Hugh   Jackman  51.0   m              6.0               8.0
2       Hugh   Jackman  51.0   m              6.0               8.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna(method = "ffill", axis = 1)

  first_name last_name   age  sex pre_movie_score post_movie_score
0        Tom     Hanks  63.0    m             8.0             10.0
1        NaN       NaN   NaN  NaN             NaN              NaN
2       Hugh   Jackman  51.0    m               m                m
3      Oprah   Winfrey  66.0    f             6.0              8.0
4       Emma     Stone  31.0    f             7.0              9.0

In [ ]:
ms.fillna(method = "bfill", axis = 1)

  first_name last_name   age  sex pre_movie_score post_movie_score
0        Tom     Hanks  63.0    m             8.0             10.0
1        NaN       NaN   NaN  NaN             NaN              NaN
2       Hugh   Jackman  51.0    m             NaN              NaN
3      Oprah   Winfrey  66.0    f             6.0              8.0
4       Emma     Stone  31.0    f             7.0              9.0

In [ ]:
ms.fillna(1, limit = 1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1          1         1   1.0   1              1.0               1.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.fillna(method = "ffill", limit = 1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
ms.replace(to_replace = "Winfrey", value = "Rhodney")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Rhodney  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.replace("Winfrey", "Rhodney")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Rhodney  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.replace("Winfrey", "Stein")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah     Stein  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.fillna(1, inplace = True)

In [ ]:
ms.replace(["Tom", 1, "Hugh", "Oprah", "Emma"], ["Emma", "Tom", 1, "Hugh", "Oprah"])

  first_name last_name   age  sex pre_movie_score post_movie_score
0       Emma     Hanks  63.0    m             8.0             10.0
1        Tom       Tom   Tom  Tom             Tom              Tom
2          1   Jackman  51.0    m             Tom              Tom
3       Hugh   Winfrey  66.0    f             6.0              8.0
4      Oprah     Stone  31.0    f             7.0              9.0

In [ ]:
ms = pd.read_csv("/content/movie_scores.csv")
ms

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.interpolate()

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN         7.333333          9.333333
2       Hugh   Jackman  51.0    m         6.666667          8.666667
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(method = "linear")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN         7.333333          9.333333
2       Hugh   Jackman  51.0    m         6.666667          8.666667
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(method = "polynomial", order = 2)

  first_name last_name        age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.000000    m         8.000000         10.000000
1        NaN       NaN  46.631579  NaN         6.500000          8.500000
2       Hugh   Jackman  51.000000    m         5.833333          7.833333
3      Oprah   Winfrey  66.000000    f         6.000000          8.000000
4       Emma     Stone  31.000000    f         7.000000          9.000000

In [ ]:
ms.interpolate(method = "nearest")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN  63.0  NaN              8.0              10.0
2       Hugh   Jackman  51.0    m              6.0               8.0
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
ms.interpolate(limit = 1)

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN         7.333333          9.333333
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(limit = 1, limit_direction = "forward")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN         7.333333          9.333333
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(limit = 1, limit_direction = "backward")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m         6.666667          8.666667
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(limit = 1, limit_direction = "both")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN         7.333333          9.333333
2       Hugh   Jackman  51.0    m         6.666667          8.666667
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(limit = 1, limit_area = "inside")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m         8.000000         10.000000
1        NaN       NaN  57.0  NaN         7.333333          9.333333
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f         6.000000          8.000000
4       Emma     Stone  31.0    f         7.000000          9.000000

In [ ]:
ms.interpolate(limit = 1, limit_area = "outside")

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

***Groupby***

In [ ]:
tp = pd.read_csv("/content/tips1.csv")

In [ ]:
tp.groupby

<bound method DataFrame.groupby of      total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

             Payer Name         CC Number Payment ID
0    Christy Cunningham  3560325168603410    Sun2959
1        Douglas Tucker  4478071379779230    Sun4608
2        Travis Walters  6011812112971322    Sun4458
3      Nathaniel Harris  4676137647685994    Sun5260
4          Tonya Carter  4832732618637221    Sun2251
..                  ...               ...        ...
239       Michael Avila  5296068606052842    Sat2657
240      Monica Sanders  3506806155565404    Sat1766
241          Keith Wong  6011891618747196    Sat3880
242        Dennis Dixon     4375220550950      Sat17
243     Michelle Hardin  3511451626698139    Thur672

[244 rows x 11 columns]>

In [ ]:
g1 = tp.groupby(by = "tip")

In [ ]:
g1.groups

{1.0: [67, 92, 111, 236], 1.01: [0], 1.1: [215], 1.17: [237], 1.25: [75, 135, 235], 1.32: [43], 1.36: [146], 1.44: [195, 218], 1.45: [30], 1.47: [233], 1.48: [126], 1.5: [57, 97, 99, 117, 130, 132, 145, 190, 217], 1.56: [53], 1.57: [12], 1.58: [224], 1.61: [168], 1.63: [147], 1.64: [105], 1.66: [1], 1.67: [16], 1.68: [121], 1.71: [10], 1.73: [148], 1.75: [242], 1.76: [58], 1.8: [118], 1.83: [82], 1.92: [222], 1.96: [8], 1.97: [70], 1.98: [62], 2.0: [6, 26, 27, 36, 61, 86, 123, 127, 128, 133, 136, 137, 138, 149, 151, 153, 154, 159, 162, 163, 169, 176, 177, 187, 196, 198, 199, 202, 210, 226, 230, 240, 241], 2.01: [68, 201], 2.02: [193], 2.03: [84, 208], 2.05: [48], 2.09: [69], 2.18: [129], 2.2: [74, 220], 2.23: [22, 209], 2.24: [40, 166], 2.3: [144], 2.31: [38, 120], 2.34: [25], 2.45: [33], 2.47: [66], 2.5: [31, 50, 100, 102, 122, 150, 161, 203, 213, 225], 2.52: [124], 2.54: [41], 2.55: [113], 2.56: [192], 2.6: [51], 2.61: [158], 2.64: [64], 2.71: [79], 2.72: [228], 2.74: [152], 2.75: [21, 139], 2.83: [131], 2.88: [229], 2.92: [119], 3.0: [13, 29, 32, 45, 49, 56, 71, 78, 80, 89, 90, 98, 101, 110, 164, 184, 207, 216, 223, 227, 231, 234, 243], 3.02: [14], 3.06: [42], 3.07: [37], 3.08: [76], 3.09: [219], 3.11: [175], 3.12: [7], 3.14: [72], 3.15: [65], 3.16: [171], 3.18: [24, 173], 3.21: [60], 3.23: [9, 205], 3.25: [94, 134], 3.27: [34], 3.31: [3], 3.35: [19], 3.39: [232], 3.4: [81], 3.41: [206], 3.48: [103, 165, 221], 3.5: [2, 18, 91, 115, 140, 160, 182, 186, 188], 3.51: [55], 3.55: [179], 3.6: [35], 3.61: [4], 3.68: [180], 3.71: [17], 3.75: [157], 3.76: [63, 108], 3.92: [15], 4.0: [77, 87, 96, 109, 112, 114, 174, 178, 189, 194, 200, 204], 4.06: [106], 4.08: [20, 104], 4.19: [191], 4.2: [125], 4.29: [107], 4.3: [28, 93], ...}

In [ ]:
g1 = tp.groupby(by = ["tip", "total_bill"]).groups
g1

{(1.0, 3.07): [67], (1.0, 5.75): [92], (1.0, 7.25): [111], (1.0, 12.6): [236], (1.01, 16.99): [0], (1.1, 12.9): [215], (1.17, 32.83): [237], (1.25, 8.51): [135], (1.25, 10.07): [235], (1.25, 10.51): [75], (1.32, 9.68): [43], (1.36, 18.64): [146], (1.44, 7.56): [195], (1.44, 7.74): [218], (1.45, 9.55): [30], (1.47, 10.77): [233], (1.48, 8.52): [126], (1.5, 8.35): [145], (1.5, 10.65): [117], (1.5, 11.17): [132], (1.5, 11.59): [217], (1.5, 12.03): [97], (1.5, 12.46): [99], (1.5, 15.69): [190], (1.5, 19.08): [130], (1.5, 26.41): [57], (1.56, 9.94): [53], (1.57, 15.42): [12], (1.58, 13.42): [224], (1.61, 10.59): [168], (1.63, 11.87): [147], (1.64, 15.36): [105], (1.66, 10.34): [1], (1.67, 10.33): [16], (1.68, 13.42): [121], (1.71, 10.27): [10], (1.73, 9.78): [148], (1.75, 17.82): [242], (1.76, 11.24): [58], (1.8, 12.43): [118], (1.83, 10.07): [82], (1.92, 8.58): [222], (1.96, 15.04): [8], (1.97, 12.02): [70], (1.98, 11.02): [62], (2.0, 7.51): [149], (2.0, 8.77): [6], (2.0, 10.09): [226], (2.0, 10.33): [136], (2.0, 10.34): [196], (2.0, 10.63): [169], (2.0, 11.38): [128], (2.0, 12.26): [133], (2.0, 12.69): [27], (2.0, 13.0): [198, 202], (2.0, 13.03): [86], (2.0, 13.13): [151], (2.0, 13.37): [26], (2.0, 13.51): [199], (2.0, 13.81): [61, 163], (2.0, 14.15): [137], (2.0, 14.48): [177], (2.0, 14.52): [127], (2.0, 15.95): [123], (2.0, 16.0): [138], (2.0, 16.21): [162], (2.0, 16.31): [36], (2.0, 16.49): [159], (2.0, 17.89): [176], (2.0, 19.77): [154], (2.0, 22.67): [241], (2.0, 24.01): [230], (2.0, 24.55): [153], (2.0, 27.18): [240], (2.0, 30.06): [210], (2.0, 30.46): [187], (2.01, 12.74): [201], (2.01, 20.23): [68], (2.02, 15.48): [193], (2.03, 15.98): [84], (2.03, 24.27): [208], (2.05, 28.55): [48], (2.09, 15.01): [69], (2.18, 22.82): [129], (2.2, 12.16): [220], (2.2, 14.73): [74], (2.23, 12.76): [209], (2.23, 15.77): [22], (2.24, 16.04): [40], (2.24, 20.76): [166], (2.3, 16.43): [144], (2.31, 11.69): [120], (2.31, 18.69): [38], (2.34, 17.81): [25], (2.45, 20.69): [33], (2.47, 16.45): [66], (2.5, 11.35): [100], (2.5, 12.54): [50], (2.5, 12.66): [161], (2.5, 13.27): [213], ...}

In [ ]:
g3 = tp.groupby(by = "tip").get_group(1.0)
g3

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.0,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
92,5.75,1.0,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
111,7.25,1.0,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
236,12.60,1.0,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032

In [ ]:
g3.mean()

<ipython-input-124-99c2298bf497>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  g3.mean()

total_bill          7.167500e+00
tip                 1.000000e+00
size                1.500000e+00
price_per_person    4.875000e+00
CC Number           3.742824e+15
dtype: float64

In [ ]:
df1 = pd.DataFrame({"id": [1, 2, 3, 4], "class": [5, 6, 7, 8]})
df1

   id  class
0   1      5
1   2      6
2   3      7
3   4      8

In [ ]:
df2 = pd.DataFrame({"id": [1, 2, 3, 4], "name": ["a", "b", "c", "d"]})
df2

   id name
0   1    a
1   2    b
2   3    c
3   4    d

In [ ]:
pd.merge(df1, df2, on = "id")

   id  class name
0   1      5    a
1   2      6    b
2   3      7    c
3   4      8    d

In [ ]:
df3 = pd.DataFrame({"id": [1, 6, 3, 4], "class": [9, 10, 11, 12]})

In [ ]:
pd.merge(df1, df3, on = "id")

   id  class_x  class_y
0   1        5        9
1   3        7       11
2   4        8       12

In [ ]:
pd.merge(df1, df3, on = "id", suffixes = ("higher", "middle"))

   id  classhigher  classmiddle
0   1            5            9
1   3            7           11
2   4            8           12

In [ ]:
pd.merge(df1, df3, on = "id", how = "left")

   id  class_x  class_y
0   1        5      9.0
1   2        6      NaN
2   3        7     11.0
3   4        8     12.0

In [ ]:
pd.merge(df1, df3, on = "id", how = "right")

   id  class_x  class_y
0   1      5.0        9
1   6      NaN       10
2   3      7.0       11
3   4      8.0       12

In [ ]:
pd.merge(df1, df3, on = "id", how = "inner")

   id  class_x  class_y
0   1        5        9
1   3        7       11
2   4        8       12

In [ ]:
pd.merge(df1, df3, on = "id", how = "outer")

   id  class_x  class_y
0   1      5.0      9.0
1   2      6.0      NaN
2   3      7.0     11.0
3   4      8.0     12.0
4   6      NaN     10.0

In [ ]:
pd.merge(df1, df3, on = "id", how = "right", indicator = True)

   id  class_x  class_y      _merge
0   1      5.0        9        both
1   6      NaN       10  right_only
2   3      7.0       11        both
3   4      8.0       12        both

In [ ]:
pd.merge(df1, df3, on = "id", how = "left", indicator = True)

   id  class_x  class_y     _merge
0   1        5      9.0       both
1   2        6      NaN  left_only
2   3        7     11.0       both
3   4        8     12.0       both

**Pandas - Concat()**

In [ ]:
s1 = pd.Series([0, 1, 2])
s2 = pd.Series([3, 4, 5])

In [ ]:
pd.concat([s1, s2], ignore_index = True)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [ ]:
DataF1 = pd.DataFrame({"id": [1, 2, 3, 4], "name": ["a", "b", "c", "d"], "class": [5, 6, 7, 8]})
DataF1

   id name  class
0   1    a      5
1   2    b      6
2   3    c      7
3   4    d      8

In [ ]:
DataF2 = pd.DataFrame({"id": [5, 6, 7, 8], "name": ["e", "f", "g", "h"], "class": [9, 10, 11, 12]})
DataF2

   id name  class
0   5    e      9
1   6    f     10
2   7    g     11
3   8    h     12

In [ ]:
pd.concat([DataF1, DataF2], ignore_index = True)

   id name  class
0   1    a      5
1   2    b      6
2   3    c      7
3   4    d      8
4   5    e      9
5   6    f     10
6   7    g     11
7   8    h     12

In [ ]:
pd.concat([DataF1, DataF2], axis = 1)

   id name  class  id name  class
0   1    a      5   5    e      9
1   2    b      6   6    f     10
2   3    c      7   7    g     11
3   4    d      8   8    h     12

In [ ]:
DataF3 = pd.DataFrame({"id": [5, 6], "name": ["e", "f"], "class": [9, 10]})
DataF3

   id name  class
0   5    e      9
1   6    f     10

In [ ]:
pd.concat([DataF1, DataF3])

   id name  class
0   1    a      5
1   2    b      6
2   3    c      7
3   4    d      8
0   5    e      9
1   6    f     10

In [ ]:
pd.concat([DataF1, DataF3], axis = 1)

   id name  class   id name  class
0   1    a      5  5.0    e    9.0
1   2    b      6  6.0    f   10.0
2   3    c      7  NaN  NaN    NaN
3   4    d      8  NaN  NaN    NaN

In [ ]:
pd.concat([DataF1, DataF3], keys = ["DataF1", "DataF2"])

          id name  class
DataF1 0   1    a      5
       1   2    b      6
       2   3    c      7
       3   4    d      8
DataF2 0   5    e      9
       1   6    f     10

In [ ]:
pd.concat([DataF1, DataF3], keys = ["DataF1", "DataF2"], ignore_index = True)

   id name  class
0   1    a      5
1   2    b      6
2   3    c      7
3   4    d      8
4   5    e      9
5   6    f     10

In [ ]:
pd.concat([DataF1, DataF3], keys = ["DataF1", "DataF2"], axis = 1)

  DataF1            DataF2
      id name class     id name class
0      1    a     5    5.0    e   9.0
1      2    b     6    6.0    f  10.0
2      3    c     7    NaN  NaN   NaN
3      4    d     8    NaN  NaN   NaN

**Join**

In [ ]:
DataF1 = pd.DataFrame({"A": [1, 2, 3], "B": [10, 20, 30]}, index = ["a", "b", "c"])
DataF1

   A   B
a  1  10
b  2  20
c  3  30

In [ ]:
DataF2 = pd.DataFrame({"C": [4, 5, 6], "D": [40, 50, 60]}, index = ["a", "b", "c"])
DataF2

   C   D
a  4  40
b  5  50
c  6  60

In [ ]:
DataF1.join(DataF2)

   A   B  C   D
a  1  10  4  40
b  2  20  5  50
c  3  30  6  60

In [ ]:
DataF3 = pd.DataFrame({"C": [4, 5], "D": [40, 50]}, index = ["a", "b"])
DataF3

   C   D
a  4  40
b  5  50

In [ ]:
DataF1.join(DataF3)

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

In [ ]:
DataF1.join(DataF3, how = "right")

   A   B  C   D
a  1  10  4  40
b  2  20  5  50

In [ ]:
DataF1.join(DataF3, how = "left")

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

**Pandas - Append**

In [ ]:
DataF1 = pd.DataFrame({"A": [1, 2, 3], "B": [10, 20, 30]})

In [ ]:
DataF2 = pd.DataFrame({"A": [4, 5, 6], "B": [40, 50, 60]})

In [ ]:
display(DataF1, DataF2)

   A   B
0  1  10
1  2  20
2  3  30

   C   D
0  4  40
1  5  50
2  6  60

In [ ]:
DataF1.append(DataF2)

<ipython-input-170-bc36faafdf82>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DataF1.append(DataF2)

   A   B
0  1  10
1  2  20
2  3  30
0  4  40
1  5  50
2  6  60

In [ ]:
DataF1.append(DataF2, ignore_index = True)

<ipython-input-171-8f0bd1a4cb4c>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DataF1.append(DataF2, ignore_index = True)

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
5  6  60

**Pandas - Pivot Table** - Pivot table stores objects in multi-index objects

In [ ]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two','two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

df

   foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [ ]:
df.pivot(index = "foo", columns = "bar", values = "baz")

bar  A  B  C
foo
one  1  2  3
two  4  5  6

In [ ]:
df.pivot(index = "foo", columns = "bar")["baz"]

bar  A  B  C
foo
one  1  2  3
two  4  5  6

In [ ]:
df.pivot(index = "foo", columns = "bar", values = ["baz", "zoo"])

    baz       zoo
bar   A  B  C   A  B  C
foo
one   1  2  3   x  y  z
two   4  5  6   q  w  t